name: Frigate (For old x86_64 CPU without AVX)
version: 0.13.2
panel_icon: "mdi:cctv"
panel_title: Frigate
slug: frigate-oldcpu
description: NVR with realtime local object detection for IP cameras
url: "https://github.com/blakeblackshear/frigate"
startup: application
boot: auto
init: false
webui: "http://[HOST]:[PORT:5000]/"
watchdog: "http://[HOST]:[PORT:5000]/"
ingress: true
ingress_port: 5000
ingress_entry: /
panel_admin: false
homeassistant_api: true
hassio_api: true
ports:
  8555/tcp: 8555
  8555/udp: 8555
  8554/tcp: null
  5000/tcp: null
  1984/tcp: null
  1935/tcp: null
ports_description:
  8555/tcp: WebRTC over tcp
  8555/udp: WebRTC over udp
  8554/tcp: RTSP Restream
  5000/tcp: Web interface (Not required for Hass.io Ingress)
  1984/tcp: go2rtc API
  1935/tcp: RTMP streams
host_network: false
devices:
  - /dev/dri/renderD128
  - /dev/apex_0
  - /dev/apex_1
  - /dev/apex_2
  - /dev/apex_3
  - /dev/dri/card0
  - /dev/vchiq
  - /dev/video10
  - /dev/video0
usb: true
video: true
tmpfs: true
full_access: false
privileged:
  - SYS_ADMIN
environment:
  CONFIG_FILE: /config/frigate.yml
schema:
  plus_api_key: password?
services:
  - "mqtt:want"
arch:
  - amd64
map:
  - "media:rw"
  - "config:rw"
